apiVersion: v2
name: shoot
description: A Helm chart for shoot - General purpose agent for Kubernetes
type: application
version: 2.4.1
appVersion: ""
home: https://github.com/giantswarm/shoot
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
sources:
  - https://github.com/giantswarm/shoot
keywords:
  - ai
  - troubleshooting
  - debugging
maintainers:
  - name: Giant Swarm
    email: team-phoenix@giantswarm.io
annotations:
  application.giantswarm.io/team: team-phoenix
