{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "shoot.fullname" . }}-readonly
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shoot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "shoot.fullname" . }}-readonly
subjects:
  - kind: ServiceAccount
    name: {{ include "shoot.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
