{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "shoot.fullname" . }}-readonly
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shoot.labels" . | nindent 4 }}
rules:
  # Flux CD CRDs
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["notification.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # GiantSwarm App resources
  - apiGroups: ["application.giantswarm.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Cluster API (CAPI) resources
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Cluster API Provider AWS (CAPA) resources
  - apiGroups: ["infrastructure.cluster.x-k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["controlplane.cluster.x-k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["bootstrap.cluster.x-k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["addons.cluster.x-k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["exp.cluster.x-k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
{{- end }}
